# Site settings
title: Simexing
email: simexing@gmail.com
description: > Zabezpečovacie systémy # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: 
github_username:

# Build settings
markdown: kramdown
